#!/usr/bin/env bash
#   Copyright Peznauts <kevin@cloudnull.com>. All Rights Reserved.
#
#   Licensed under the Apache License, Version 2.0 (the "License"); you may
#   not use this file except in compliance with the License. You may obtain
#   a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#   WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#   License for the specific language governing permissions and limitations
#   under the License.

if [[ "${LINKER_INIT:-false}" = true ]]; then
  /linker/bin/linker-db-sync
fi

/linker/bin/uwsgi --enable-threads \
                  --plugin=python3 \
                  --chdir=/linker \
                  --module=linker:APP \
                  --processes=4 \
                  --threads=2 \
                  --virtualenv=/linker \
                  --socket=:5000 \
                  --protocol=http \
                  --vacuum \
                  --die-on-term \
                  --master
