#!/usr/bin/env bash

/linker/bin/linker-db-sync
/linker/bin/uwsgi --enable-threads \
                  --plugin=python3 \
                  --chdir=/linker \
                  --module=linker:app \
                  --virtualenv=/linker \
                  --socket=:5000 \
                  --protocol=http \
                  --vacuum \
                  --die-on-term \
                  --master
